# app/controllers/api/v1/custom_tokens_controller.rb
# =========================================================================
# ADVANCED OAUTH COOKIE-ISOLATION TOKEN CONTROLLER (METADATA EXTENDED)
# =========================================================================
module Api
  module V1
    class CustomTokensController < Doorkeeper::TokensController
      include ActionController::Cookies

      skip_before_action :authenticate_user!, raise: false
      skip_before_action :ensure_admin_access, raise: false
      skip_before_action :sync_user_presence_and_activity, raise: false

      # --- Action Endpoints ---

      # POST /api/v1/oauth/token
      def create
        # Enforce parameter mappings onto both standard params and raw rack request environments!
        if params[:grant_type] == "refresh_token" || params.dig(:custom_token, :grant_type) == "refresh_token"
          cookie_token = cookies.encrypted[:_refresh_token]

          if cookie_token.present?
            params[:refresh_token] = cookie_token
            request.parameters[:refresh_token] = cookie_token
          end
        end

        super
        set_refresh_token_cookie

        if response.successful?
          begin
            body_json = JSON.parse(response.body)

            # Securely locate the database token record generated by Doorkeeper
            token_object = Doorkeeper::AccessToken.find_by(token: body_json["access_token"])
            active_user = User.find_by(id: token_object&.resource_owner_id)

            # Package unified metadata profiles via your new database level association
            user_payload = if active_user
              # ✅ FIXED: Safely trap schema discrepancies for notification flags (like read vs read_at)
              # This ensures the authentication block passes even if notification columns change later!
              unread_count = begin
                if active_user.notifications.respond_to?(:unread)
                  active_user.notifications.unread.count
                elsif active_user.notifications.column_names.include?("read_at")
                  active_user.notifications.where(read_at: nil).count
                elsif active_user.notifications.column_names.include?("read")
                  active_user.notifications.where(read: false).count
                else
                  active_user.notifications.count
                end
              rescue => e
                0
              end

              {
                username: active_user.username,
                rating: active_user.rating,
                cefr_level: active_user.level&.name || "B2",
                unread_notifications_count: unread_count
              }
            else
              nil
            end

            # Merges token identifiers and user attributes hashes together
            extended_body = {
              access_token: body_json["access_token"],
              user: user_payload
            }

            self.response_body = extended_body.to_json
          rescue JSON::ParserError => e
            Rails.logger.error "OAUTH JSON Parse Exception: #{e.message}"
          end
        end
      end

      private

      # Extract token metrics from Doorkeeper result parameters to build cookies
      def set_refresh_token_cookie
        return unless authorize_response.is_a?(Doorkeeper::OAuth::TokenResponse)

        token_object = authorize_response.token
        return unless token_object&.refresh_token.present?

        cookies.encrypted[:_refresh_token] = {
          value: token_object.refresh_token,
          httponly: true,
          secure: true, # Must be true when SameSite is :none
          same_site: :none,
          expires_at: 14.days.from_now, # Used by low-level metal controllers
          expires: 14.days.from_now     # Used by standard action controllers
        }
      end
    end
  end
end
